actor/api/v1/urls.py
from django.urls import path
from .views import list,get_actor_details,create_actor,update_actor,delete_actor

urlpatterns = [
    path('/',list,name='list'),
    path('/create',create_actor,name='create_actor'),
    path('/<pk>/update',update_actor,name='update_actor'),
    path('/<pk>/delete',delete_actor,name='delete_actor'),
    path('/<pk>',get_actor_details,name='actor_details'),


]

actor/urls.py
from django.urls import path
from .views import getActorsList,createActor,updateActor,deleteActor,showActor
app_name='actor'
urlpatterns = [
    path('',getActorsList,name='getActorsList'),
    path('create',createActor,name='createActor'),
    path('update/<pk>',updateActor,name='updateActor'),
    path('delete/<pk>',deleteActor,name='deleteActor'),
    path('<pk>',showActor,name='showActor'),


    # path('movies/',include('movie.urls'))
]

movies_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import  include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('actors/', include('actor.urls')),
    path('movies/', include('movie.urls')),
    path('api/v1/movies',include('movie.api.v1.urls')),
    path('api/v1/actors',include('actor.api.v1.urls')),
    path('api/v1/account/',include('account.api.v1.urls')),
    path('',include('django.contrib.auth.urls')),

    path('',include('account.urls'))
]
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actor/models.py
from django.db import models


class Actor(models.Model):
    g = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    name = models.CharField(verbose_name='Actor Name', max_length=30)
    gender = models.CharField(choices=g,max_length=6 ,default='M')
    picture = models.ImageField(upload_to='actor')
    birth_date= models.DateField(null=True)

    def __str__(self):
        return self.name

actor/forms.py
from django.forms import ModelForm
from .models import Actor


class ActorForm(ModelForm):
    class Meta:
        model = Actor
        fields = '__all__'

actor/api/v1/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from actor.models import Actor
from .serializer import ActorSerializer,ActorCreateSerializer
from rest_framework.decorators import permission_classes
from .permissions import GroupPermission

@api_view(['GET'])
@permission_classes([GroupPermission])
def list(request):

    actors = Actor.objects.all()
    ser=ActorSerializer(instance=actors,many=True)
    return Response(data=ser.data, status=status.HTTP_200_OK)

@api_view(['Get'])
def get_actor_details(request,pk):
    actor = Actor.objects.get(pk=pk)
    ser = ActorSerializer(instance=actor)
    return Response(data=ser.data, status=status.HTTP_200_OK)
@api_view(['POST'])
def create_actor(request):

        serializer = ActorCreateSerializer(data=request.data)

        if (serializer.is_valid()):
            serializer.save()
            return Response(data=serializer.data,status=status.HTTP_201_CREATED)
        else:
            return Response(data=serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@api_view(['PUT','PATCH'])
def update_actor(request,pk):
        actor = Actor.objects.get(pk=pk)
        if(request.method == 'PUT'):
            serializer = ActorCreateSerializer(data=request.data,instance=actor)
        else:
            serializer = ActorCreateSerializer(data=request.data, instance=actor,partial=True)
        if (serializer.is_valid()):
            serializer.save()
            return Response(data=serializer.data,status=status.HTTP_201_CREATED)
        else:
            return Response(data=serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@api_view(['DELETE'])
def delete_actor(request,pk):
    if Actor.objects.get(pk=pk).delete():
        return Response(data={'detail':'actor deleted successfully'},status=status.HTTP_204_NO_CONTENT)

actor/views.py
from django.shortcuts import render, redirect , reverse


from .forms import ActorForm
from .models import Actor
from django.contrib.auth.decorators import login_required
def getActorsList(request):
    actors=Actor.objects.all()
    for actor in actors:
        print(f'from actors list {actor.picture}')
    return render(request,'actor/actors_list.html',context={'actors':actors})
@login_required
def createActor(request):
    method = 'create'
    print(request.method)
    if request.method == 'GET':
        actorForm = ActorForm(files=request.FILES)
    elif request.method == 'POST':
        actorForm = ActorForm(request.POST,files=request.FILES)
        if actorForm.is_valid():
            actorForm.save()
            return redirect(reverse('actor:getActorsList'))
    return render(request,'actor/actor_form.html',context={'form':actorForm,'method':method})

def deleteActor(request,pk):
    Actor.objects.get(pk=pk).delete()
    return redirect(reverse('actor:getActorsList'))

def updateActor(request,pk):
    method='update'
    actor = Actor.objects.get(pk=pk)
    if request.method == 'GET':
        actorForm = ActorForm(instance=actor,files=request.FILES)
        return render(request, 'actor/actor_form.html', context={'form': actorForm, 'method': method, 'actor': actor})
    elif request.method == 'POST':
         actorForm = ActorForm(request.POST,instance=actor,files=request.FILES)
         if actorForm.is_valid():
            actorForm.save()
            return redirect(reverse('actor:getActorsList'))


def showActor(request,pk):
    actor = Actor.objects.get(pk=pk)
    print(f'from show actor {actor.picture}')
    return render(request,'actor/actor_details.html',context={'actor':actor})

actor/templates/actor/actor_details.html
{% extends 'general_templates/base.html' %}

{% block title %} movies list {% endblock %}

{% block content%}
<div class="card" xmlns:>
  <h5 class="card-header">{{actor.name}}</h5>
  <div class="card-body">
    <p class="card-text">Gender : {{actor.gender}}</p>
    <p class="card-text">Profile Picture : <img height="10%" width="10%" src="{{request.scheme}}://{{request.get_host}}{{actor.picture.url}}"></p>
  </div>
</div>

{% endblock %}

actor/templates/actor/actor_form.html
{% extends 'general_templates/base.html' %}

{% block title %} Actors list {% endblock %}

{% block content%}
{% if method == 'create'%}
<form method="POST" action="{% url 'actor:createActor' %}" enctype="multipart/form-data">
{% else %}
   <form method="POST" action="{% url 'actor:updateActor' actor.pk %}" enctype="multipart/form-data">
       {% endif%}
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success" type="submit">submit</button>
</form>

{% endblock %}

actor/templates/actor/actors_list.html
{% extends 'general_templates/base.html' %}
{% block title %}actors list {% endblock %}

{% block content %}

<h1>actors list</h1>
<table class="table table-striped">
<thead>
<th>Name</th>
<th>Gender</th>
<th>Profile Picture</th>

<th>....</th>
</thead>
<tbody>
{% for actor in actors%}
<tr>
    <td>{{actor.name}}</td>
    <td>{{actor.gender}}</td>

    <td><img width="10%" height="10%" src="{{request.scheme}}://{{request.get_host}}{{actor.picture.url}}"></td>


   <td><a class="btn btn-dark" href="{% url 'actor:showActor' actor.pk %}">Details</a></td>
    {% if request.user.is_authenticated %}
    <td><a class="btn btn-danger" href="{% url 'actor:deleteActor' actor.pk %}">Delete</a></td>
    <td><a class="btn btn-primary" href="{% url 'actor:updateActor' actor.pk %}">Update</a></td>
    {% endif %}
</tr>
{% endfor %}


</tbody>
</table>

<a href="{% url 'actor:createActor' %}" class="btn btn-success">Create Actor</a>
{% endblock %}