actor/urls.py
from django.urls import path
from .views import getActorsList,createActor,updateActor,deleteActor,showActor
app_name='actor'
urlpatterns = [
    path('',getActorsList,name='getActorsList'),
    path('create',createActor,name='createActor'),
    path('update/<pk>',updateActor,name='updateActor'),
    path('delete/<pk>',deleteActor,name='deleteActor'),
    path('<pk>',showActor,name='showActor'),


    # path('movies/',include('movie.urls'))
]

movie/api/v1/urls.py
from django.urls import path
from .views import hello,list,get_movie_details,create_movie,update_movie,delete_movie

urlpatterns = [
    path('/hello',hello, name='hello'),
    path('/',list,name='list'),
    path('/create',create_movie,name='create_movie'),
    path('/<pk>/update',update_movie,name='update_movie'),
    path('/<pk>/delete',delete_movie,name='delete_movie'),
    path('/<pk>',get_movie_details,name='movie_details'),


]

movie/urls.py
from django.urls import path
from .views import getMoviesList , createMovie,deleteMovie,updateMovie,showMovie
app_name='movie'

urlpatterns = [
    path('',getMoviesList,name='getMoviesList'),
    path('create',createMovie, name='createMovie'),
    path('delete/<pk>',deleteMovie,name='deleteMovie'),
    path('update/<pk>',updateMovie,name='updateMovie'),
    path('<pk>',showMovie,name='showMovie')


]

movies_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import  include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('actors/', include('actor.urls')),
    path('movies/', include('movie.urls')),
    path('api/v1/movies',include('movie.api.v1.urls')),
    path('api/v1/actors',include('actor.api.v1.urls')),
    path('api/v1/account/',include('account.api.v1.urls')),
    path('',include('django.contrib.auth.urls')),

    path('',include('account.urls'))
]
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/models.py
from django.db import models
from actor.models import Actor
from director.models import Director
# Create your models here.
class Movie(models.Model):
    name = models.CharField(verbose_name='Movie Name',max_length=30)
    production_year = models.IntegerField()
    creation_time = models.DateField()
    actor = models.ManyToManyField(Actor)
    director = models.ForeignKey(Director,verbose_name='Director Name', on_delete=models.CASCADE)
    update_time = models.DateField(auto_now=True)


    def __str__(self):
        return f'actors :  {self.name }'

movie/forms.py
from django.forms import ModelForm
from .models import Movie


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

movie/api/v1/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from movie.models import Movie
from .serializer import MovieSerializer,MovieCreateSerializer
@api_view(['GET'])
def hello (request):
    return Response(data={},status=status.HTTP_200_OK)

@api_view(['GET'])
def list(request):

    movies = Movie.objects.all()
    ser=MovieSerializer(instance=movies,many=True)
    return Response(data=ser.data, status=status.HTTP_200_OK)

@api_view(['Get'])
def get_movie_details(request,pk):
    movie = Movie.objects.get(pk=pk)
    ser = MovieSerializer(instance=movie)
    return Response(data=ser.data, status=status.HTTP_200_OK)
@api_view(['POST'])
def create_movie(request):

        serializer = MovieCreateSerializer(data=request.data)

        if (serializer.is_valid()):
            serializer.save()
            return Response(data=serializer.data,status=status.HTTP_201_CREATED)
        else:
            return Response(data=serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@api_view(['PUT','PATCH'])
def update_movie(request,pk):
        movie = Movie.objects.get(pk=pk)
        if(request.method == 'PUT'):
            serializer = MovieCreateSerializer(data=request.data,instance=movie)
        else:
            serializer = MovieCreateSerializer(data=request.data, instance=movie,partial=True)
        if (serializer.is_valid()):
            serializer.save()
            return Response(data=serializer.data,status=status.HTTP_201_CREATED_OK)
        else:
            return Response(data=serializer.errors,status=status.HTTP_400_BAD_REQUEST)

@api_view(['DELETE'])
def delete_movie(request,pk):
    if Movie.objects.get(pk=pk).delete():
        return Response(data={'detail':'movie deleted successfully'},status=status.HTTP_204_NO_CONTENT)

movie/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from actor.models import Actor
from .models import Movie
from .forms import MovieForm
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, JsonResponse
# Create your views here.
def getMoviesList(request):
    movies = Movie.objects.all()
    #how to get actors in each movie
    # for movie in movies :
    #     for actor in movie.actor.all():
    #         print(actor.name)

    return render(request, 'movie/movies_list.html',context={'movies':movies})
@login_required
def createMovie(request):
    method='create'
    if request.method =='GET' :
        movieForm = MovieForm()
    elif    request.method == 'POST' :
        movieForm = MovieForm(request.POST)
        if movieForm.is_valid():
            movieForm.save()
            return redirect(reverse('movie:getMoviesList'))
    return render(request,'movie/movie_form.html',context={'form':movieForm,'method':method})


def deleteMovie(request,pk):

    Movie.objects.get(pk=pk).delete()
    return(getMoviesList(request))

def updateMovie(request,pk):
    method='update'
    movie= Movie.objects.get(pk=pk)
    if request.method == 'GET':
        movieForm = MovieForm(instance=movie)
    elif request.method == 'POST':
        movieForm = MovieForm(request.POST, instance=movie)
        if movieForm.is_valid():
            movieForm.save()
            return redirect(reverse('movie:getMoviesList'))
    return render(request, 'movie/movie_form.html', context={'form': movieForm,'movie':movie,'method':method})

def showMovie(request,pk):
    movie=Movie.objects.get(pk=pk)
    actors =[]
    for actor in movie.actor.all():
        actors.append(actor)
    return render(request,'movie/movie_details.html',context={'movie':movie,'actors':actors})

movie/templates/movie/movie_details.html
{% extends 'general_templates/base.html' %}

{% block title %} movies list {% endblock %}

{% block content%}
<div class="card">
  <h5 class="card-header">{{movie.name}}</h5>
  <div class="card-body">
    <p class="card-text">production year : {{movie.production_year}}</p>
      <p class="card-text"> actors : <br>
          {%for actor in actors %}
          <ul>
                <li>{{actor}}</li>
          </ul>

          {% endfor %}
      </p>
    <p class="card-text">creation time : {{movie.creation_time}}</p>
  </div>
</div>

{% endblock %}

movie/templates/movie/movie_form.html
{% extends 'general_templates/base.html' %}

{% block title %} movies list {% endblock %}

{% block content%}
{% if method == 'create' %}
<form method="post" action="{% url 'movie:createMovie'  %}" >
{%else%}
    <form method="post" action="{% url 'movie:updateMovie' movie.pk %}">
 {%endif%}
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success" type="submit">submit</button>
</form>

{% endblock %}

movie/templates/movie/movies_list.html
{% extends 'general_templates/base.html' %}

{% block title %} movies list {% endblock %}

{% block content%}

<h1>movies list</h1>
<table class="table table-striped">
<thead>
<th>Movie Name</th>
<th>Production Year</th>
<th>Creation Time</th>
<th>Actors</th>
<th>Update Time</th>
<th>....</th>
</thead>
<tbody>
{% for movie in movies%}
<tr>
    <td>{{movie.name}}</td>
    <td>{{movie.production_year}}</td>
    <td>{{movie.creation_time}}</td>
    <td>
      {% for actor in movie.actor.all %}
        <ul>
            <li>{{actor.name}}</li>
        </ul>
        {% endfor %}
    </td>
    <td>{{movie.update_time}}</td>
    <td><a class="btn btn-light" href="{% url 'movie:showMovie' movie.id %}">Details</a></td>
    {% if request.user.is_authenticated%}
    <td><a class="btn btn-danger" href="{% url 'movie:deleteMovie' movie.id %}">Delete</a></td>
    <td><a class="btn btn-primary" href="{% url 'movie:updateMovie' movie.id %}">Update</a></td>
    {% endif %}
</tr>
{% endfor %}


</tbody>
</table>

<a href="{% url 'movie:createMovie' %}" class="btn btn-success">Create Movie</a>


{% endblock %}